
services:

  mongodb_auth:
    image: mongo
    container_name: mongo_auth
    env_file: "./.env"
    ports:
      - ${AUTH_MONGODB_PORT}:${AUTH_MONGODB_PORT}
    networks:
      - services 

  mongodb_client:
    image: mongo
    container_name: mongo_client
    env_file: "./.env"
    ports:
      - ${CLIENT_MONGODB_PORT}:${CLIENT_MONGODB_PORT}
    networks:
      - services 

  server:
    image: valeevilja/oauth2_server:v1
    env_file: "./.env"
    container_name: ${SERVER}
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/server
    networks:
      - services 
    depends_on:
      - mongodb_auth

  client:
    image: valeevilja/oauth2_client:v1
    env_file: "./.env"
    container_name: ${CLIENT}
    restart: always
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/client
    networks:
      - services 
    depends_on:
      - mongodb_client

  resource:
    image: valeevilja/oauth2_resource:v1
    env_file: "./.env"
    container_name: ${RESOURCE}
    restart: always
    ports:
      - ${RESOURCE_PORT}:${RESOURCE_PORT}
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/resource
    networks:
      - services 
    depends_on:
      - mongodb  

volumes:
  mongodbdata:
    driver: local

networks:
  services: