
services:

  mongodb:
    image: mongo
    container_name: mongo
    env_file: "./.env"
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - services 

  server:
    image: valeevilja/oauth2_server:v1
    env_file: "./.env"
    container_name: ${SERVER}
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/server
    networks:
      - services 
    depends_on:
      - mongodb

  client:
    image: valeevilja/oauth2_client:v1
    env_file: "./.env"
    container_name: ${CLIENT}
    restart: always
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/client
    networks:
      - services 
    depends_on:
      - mongodb

  resource:
    image: valeevilja/oauth2_resource:v1
    env_file: "./.env"
    container_name: ${RESOURCE}
    restart: always
    ports:
      - ${RESOURCE_PORT}:${RESOURCE_PORT}
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/resource
    networks:
      - services 
    depends_on:
      - mongodb  

volumes:
  mongodbdata:
    driver: local

networks:
  services: