version: '3.8'

services:

  mongodb:
    image: mongo
    container_name: db
    env_file: 
      - path: ./.env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - services 

  server:
    image: valeevilja/oauth2_server:v1
    container_name: server
    restart: always
    ports:
      - 9001:9001
    env_file:
      - ./.env
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/server
    networks:
      - services 
    depends_on:
      - mongodb

  client:
    image: valeevilja/oauth2_client:v1
    container_name: client
    restart: always
    ports:
      - 9000:9000
    env_file:
      - ./.env
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/client
    networks:
      - services 
    depends_on:
      - mongodb

  resource:
    image: valeevilja/oauth2_resource:v1
    container_name: resource
    restart: always
    ports:
      - 9002:9002
    env_file:
      - ./.env
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_HOST=${MONGODB_HOST}
    volumes:
      - ./:/resource
    networks:
      - services 
    depends_on:
      - mongodb  

volumes:
  mongodbdata:
    driver: local

networks:
  services: